### ISSUE TITLE
As a user, I want to be able to view my course status so that I can know if I pass or fail.

### ISSUE THREAD

**Issue by hale2ian** [marktmng/sis_backend#18]
- [x] assign user story
- [x] create new branch
- [x] export production data from vercel online DB
- [x] edit settings.py to point application from online vercel DB to local DB for testing and to avoid affecting production data
- [x] import vercel DB production data to local DB
- [x] edit models.py to add new field, student mark
- [x] migration to update local DB of new added field in models.py
- [x] Postman testing of local DB
- [x] edit settings.py to point application from local DB to online vercel DB for applying models.py change to online vercel DB
- [x] migration to update online vercel DB of new added field in models.py
- [x] Postman testing of online vercel DB

**Comment by hale2ian** [comment]
- [x] Selenium/Postman testing passed
- [x] check commits
- [x] check code changes
- [x] provide feedbacks/reviews
- [x] provide summary of changes made by developer
- [x] Approve code change

**Comment by marktmng** [comment]
Hey developer, testing and building is perfectly working, you are now working your local database can you move to the online version please.
